name: medicine
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  adaptive_shimmer: ^0.0.5
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dashed_circular_progress_bar: ^0.0.6
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  flutter_timer_countdown: ^1.0.5
  get: ^4.6.6
  lottie: ^3.0.0
  persian_number_utility: ^1.1.4
  shamsi_date: ^1.0.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/

  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/YekanBakhFaNum-Regular.ttf
          weight: 400
        - asset: assets/fonts/YekanBakhFaNum-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/YekanBakhFaNum-Bold.ttf
          weight: 700
        - asset: assets/fonts/YekanBakhFaNum-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
